-- The six cleanup-review inbox rows in this batch were synthetic presentation
-- fixtures. Their context explicitly records that they have no real report or
-- money and must be removed before payments are enabled. Keep the production
-- inbox limited to cases generated by real workflows.

do $$
declare
  preview_case_count integer;
begin
  select count(*)
  into preview_case_count
  from public.cleanup_admin_cases
  where context @> jsonb_build_object(
    'preview', true,
    'preview_batch', 'cleanup-review-inbox-v2',
    'no_real_money', true,
    'no_real_report', true,
    'remove_before_payments_enabled', true
  )
    and title like '[Preview]%';

  if preview_case_count not in (0, 6) then
    raise exception
      'Expected zero or six cleanup-review preview cases, found %',
      preview_case_count;
  end if;

  delete from public.cleanup_admin_actions
  where case_id in (
    select id
    from public.cleanup_admin_cases
    where context @> jsonb_build_object(
      'preview', true,
      'preview_batch', 'cleanup-review-inbox-v2',
      'no_real_money', true,
      'no_real_report', true,
      'remove_before_payments_enabled', true
    )
      and title like '[Preview]%'
  );

  delete from public.cleanup_admin_cases
  where context @> jsonb_build_object(
    'preview', true,
    'preview_batch', 'cleanup-review-inbox-v2',
    'no_real_money', true,
    'no_real_report', true,
    'remove_before_payments_enabled', true
  )
    and title like '[Preview]%';
end;
$$;
